-- ============================================================
-- V2.0-6 增量脚本：新建「系统设置」多设备同步表
--
-- 用法：Supabase 控制台 → 左侧 SQL Editor → New query
--       → 整段粘贴进来 → Run（或 Cmd/Ctrl + Enter）
--
-- 脚本幂等，重复执行不会有副作用。执行成功后刷新 ERP 页面即可生效。
-- ============================================================

-- 一条 key 一行：公司抬头 / 打印设置 / 价格规则 / 品牌图标 / 菜单排序
CREATE TABLE IF NOT EXISTS "systemSettings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "key" text NOT NULL UNIQUE,
  "value" jsonb,
  "updatedAt" text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_syssettings_key ON "systemSettings"("key");

-- 让前端（publishable / anon key）可读写。
-- 与其它业务表一致：第一版暂不开 RLS，应用层自有登录保护。
GRANT ALL ON "systemSettings" TO anon;
GRANT ALL ON SEQUENCE "systemSettings_id_seq" TO anon;

-- 验证：执行后应看到 systemSettings 一行
SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename = 'systemSettings';
