-- ============================================================
-- 家电批发进销存 ERP · Supabase 建表脚本（V1.1 迁移第一步）
-- 24 张业务表，字段名与前端 TS 类型保持 camelCase 一致（用双引号引用）
-- 第一版：暂不开 RLS（等接入 Supabase Auth 后再做行级权限）
-- ============================================================

-- ---------- 基础档案 ----------
CREATE TABLE IF NOT EXISTS "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" text, "employeeNo" text, "name" text NOT NULL, "phone" text,
  "password" text NOT NULL, "role" text NOT NULL DEFAULT 'sales',
  "status" text NOT NULL DEFAULT 'active',
  "dept" text, "position" text, "joinDate" text, "remark" text,
  "avatar" text, "lastLoginAt" text, "system" boolean DEFAULT false,
  "createdAt" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "customers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL, "contact" text, "phone" text, "address" text,
  "level" text DEFAULT '零售', "creditLimit" numeric DEFAULT 0,
  "paymentTerm" text DEFAULT '现结',
  "loginPhone" text, "loginPassword" text,
  "status" text DEFAULT 'active', "remark" text,
  "invoiceTitle" text, "taxNo" text, "invoiceAddress" text,
  "invoicePhone" text, "bankName" text, "bankAccount" text
);

CREATE TABLE IF NOT EXISTS "suppliers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL, "contact" text, "phone" text, "address" text,
  "paymentTerm" text DEFAULT '现结', "remark" text,
  "invoiceTitle" text, "taxNo" text, "invoiceAddress" text,
  "invoicePhone" text, "bankName" text, "bankAccount" text
);

CREATE TABLE IF NOT EXISTS "products" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "brand" text, "model" text, "category" text, "spec" text, "unit" text,
  "purchasePrice" numeric DEFAULT 0, "wholesalePrice" numeric DEFAULT 0,
  "retailPrice" numeric DEFAULT 0, "warnStock" numeric DEFAULT 0,
  "status" text DEFAULT 'active', "remark" text,
  "extra" jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS "locations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL, "remark" text, "createdAt" text
);

CREATE TABLE IF NOT EXISTS "stock" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productId" BIGINT NOT NULL, "quantity" numeric DEFAULT 0, "updatedAt" text
);

CREATE TABLE IF NOT EXISTS "locationStock" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productId" BIGINT NOT NULL, "locationId" BIGINT NOT NULL, "quantity" numeric DEFAULT 0
);

-- ---------- 采购 ----------
CREATE TABLE IF NOT EXISTS "purchaseOrders" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderNo" text NOT NULL, "supplierId" BIGINT, "purchaserId" BIGINT,
  "orderDate" text, "status" text DEFAULT 'pending',
  "totalAmount" numeric DEFAULT 0, "payStatus" text DEFAULT 'unpaid',
  "remark" text
);

CREATE TABLE IF NOT EXISTS "purchaseOrderItems" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "purchaseOrderId" BIGINT NOT NULL, "productId" BIGINT,
  "quantity" numeric DEFAULT 0, "price" numeric DEFAULT 0,
  "subtotal" numeric DEFAULT 0, "isGift" boolean DEFAULT false
);

-- ---------- 销售 ----------
CREATE TABLE IF NOT EXISTS "saleOrders" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderNo" text NOT NULL, "customerId" BIGINT, "salesId" BIGINT,
  "orderDate" text, "status" text DEFAULT 'pending',
  "totalAmount" numeric DEFAULT 0, "receiveStatus" text DEFAULT 'unreceived',
  "remark" text, "priceMode" text DEFAULT 'wholesale'
);

CREATE TABLE IF NOT EXISTS "saleOrderItems" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "saleOrderId" BIGINT NOT NULL, "productId" BIGINT,
  "quantity" numeric DEFAULT 0, "price" numeric DEFAULT 0,
  "subtotal" numeric DEFAULT 0, "isGift" boolean DEFAULT false
);

-- ---------- 出入库 / 调拨 / 盘点 ----------
CREATE TABLE IF NOT EXISTS "stockRecords" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" text, "refOrderId" BIGINT, "productId" BIGINT,
  "quantity" numeric DEFAULT 0, "operatorId" BIGINT, "createdAt" text,
  "batchNo" text, "locationId" BIGINT, "remark" text
);

CREATE TABLE IF NOT EXISTS "transferOrders" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderNo" text, "fromLoc" BIGINT, "toLoc" BIGINT, "date" text,
  "operatorId" BIGINT, "status" text DEFAULT 'done'
);

CREATE TABLE IF NOT EXISTS "transferItems" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transferOrderId" BIGINT NOT NULL, "productId" BIGINT, "quantity" numeric DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "stocktakes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderNo" text, "locationId" BIGINT, "date" text,
  "operatorId" BIGINT, "status" text DEFAULT 'done'
);

CREATE TABLE IF NOT EXISTS "stocktakeItems" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "stocktakeId" BIGINT NOT NULL, "productId" BIGINT,
  "systemQty" numeric DEFAULT 0, "actualQty" numeric DEFAULT 0
);

-- ---------- 退换货 ----------
CREATE TABLE IF NOT EXISTS "returnOrders" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderNo" text, "kind" text, "refOrderId" BIGINT, "refOrderNo" text,
  "partyId" BIGINT, "date" text, "operatorId" BIGINT,
  "status" text DEFAULT 'done', "totalAmount" numeric DEFAULT 0, "remark" text
);

CREATE TABLE IF NOT EXISTS "returnItems" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "returnOrderId" BIGINT NOT NULL, "productId" BIGINT,
  "quantity" numeric DEFAULT 0, "price" numeric DEFAULT 0,
  "amount" numeric DEFAULT 0, "reason" text
);

-- ---------- 财务 ----------
CREATE TABLE IF NOT EXISTS "payments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" text, "refOrderId" BIGINT, "counterpartyId" BIGINT,
  "amount" numeric DEFAULT 0, "payDate" text, "operatorId" BIGINT, "remark" text
);

CREATE TABLE IF NOT EXISTS "ledgerEntries" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderNo" text, "direction" text, "category" text, "amount" numeric DEFAULT 0,
  "counterparty" text, "entryDate" text, "operatorId" BIGINT, "remark" text,
  "linkDocType" text, "linkDocNo" text, "createdAt" text
);

-- ---------- 系统 ----------
CREATE TABLE IF NOT EXISTS "auditLogs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "operatorId" BIGINT, "action" text, "detail" text, "createdAt" text
);

CREATE TABLE IF NOT EXISTS "rolePerms" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" text NOT NULL, "modules" text[] DEFAULT '{}', "updatedAt" text
);

-- ---------- 系统设置（多设备同步，V2.0-6） ----------
-- 电脑 / 手机共用同一份系统设置：公司抬头、打印设置、价格规则、
-- 品牌与 App 图标、菜单排序。一条 key 一行，value 用 jsonb 存任意结构。
-- 同步策略：以 updatedAt 做 last-write-wins；localStorage 仍是本机缓存，
-- 表不存在或离线时自动降级为「仅本机生效」，不影响使用。
CREATE TABLE IF NOT EXISTS "systemSettings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "key" text NOT NULL UNIQUE,
  "value" jsonb,
  "updatedAt" text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_syssettings_key ON "systemSettings"("key");

-- ---------- 报价单 ----------
CREATE TABLE IF NOT EXISTS "quoteOrders" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderNo" text, "customerId" BIGINT DEFAULT 0, "customerName" text,
  "quoteDate" text, "status" text DEFAULT 'draft',
  "totalAmount" numeric DEFAULT 0, "validDays" numeric, "remark" text,
  "salesId" BIGINT, "convertedSaleOrderId" BIGINT, "convertedSaleNo" text,
  "createdAt" text
);

CREATE TABLE IF NOT EXISTS "quoteOrderItems" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "quoteOrderId" BIGINT NOT NULL, "productId" BIGINT,
  "quantity" numeric DEFAULT 0, "price" numeric DEFAULT 0, "subtotal" numeric DEFAULT 0
);

-- ---------- 常用查询索引 ----------
CREATE INDEX IF NOT EXISTS idx_products_brand ON "products"("brand");
CREATE INDEX IF NOT EXISTS idx_products_category ON "products"("category");
CREATE INDEX IF NOT EXISTS idx_products_status ON "products"("status");
CREATE INDEX IF NOT EXISTS idx_stock_product ON "stock"("productId");
CREATE INDEX IF NOT EXISTS idx_locstock_prod_loc ON "locationStock"("productId","locationId");
CREATE INDEX IF NOT EXISTS idx_po_no ON "purchaseOrders"("orderNo");
CREATE INDEX IF NOT EXISTS idx_po_supplier ON "purchaseOrders"("supplierId");
CREATE INDEX IF NOT EXISTS idx_poi_order ON "purchaseOrderItems"("purchaseOrderId");
CREATE INDEX IF NOT EXISTS idx_so_no ON "saleOrders"("orderNo");
CREATE INDEX IF NOT EXISTS idx_so_customer ON "saleOrders"("customerId");
CREATE INDEX IF NOT EXISTS idx_soi_order ON "saleOrderItems"("saleOrderId");
CREATE INDEX IF NOT EXISTS idx_sr_batch ON "stockRecords"("batchNo");
CREATE INDEX IF NOT EXISTS idx_sr_product ON "stockRecords"("productId");
CREATE INDEX IF NOT EXISTS idx_sr_created ON "stockRecords"("createdAt");
CREATE INDEX IF NOT EXISTS idx_payments_ref ON "payments"("refOrderId");
CREATE INDEX IF NOT EXISTS idx_ledger_date ON "ledgerEntries"("entryDate");
CREATE INDEX IF NOT EXISTS idx_audit_created ON "auditLogs"("createdAt");
CREATE INDEX IF NOT EXISTS idx_quote_no ON "quoteOrders"("orderNo");

-- ---------- 让匿名（publishable key）可读写 ----------
-- 第一版：应用层自有登录保护；后续接入 Supabase Auth 后改 RLS 策略
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon;
