/**
 * 「系统设置」多设备同步的建表 SQL（V2.0-10）
 * ----------------------------------------------------------------
 * 为什么把它搬进前端代码：云端表 systemSettings 属于 DDL，前端用的
 * publishable / anon key **没有建表权限**，必须由用户在 Supabase 控制台
 * 的 SQL Editor 手工执行一次。
 *
 * 而部署出去的网站里并没有 supabase/*.sql 这些文件，用户从手机上看不到、
 * 也拷不出来 —— 所以设置页直接提供「复制建表 SQL」按钮，把这段原文塞进剪贴板，
 * 用户只需要：打开 SQL Editor → 粘贴 → Run → 回来刷新。
 *
 * ⚠️ 这段内容必须与 `supabase/migrate_v2.0-6_system_settings.sql` 一字不差，
 *    `tests/settings-cloud-sync.test.ts` 会逐字符比对，改一处必须两处一起改。
 */
import { SUPABASE_URL } from '../db/supabaseClient'

export const SYSTEM_SETTINGS_SQL = `-- ============================================================
-- V2.0-6 增量脚本：新建「系统设置」多设备同步表
--
-- 用法：Supabase 控制台 → 左侧 SQL Editor → New query
--       → 整段粘贴进来 → Run（或 Cmd/Ctrl + Enter）
--
-- 脚本幂等，重复执行不会有副作用。执行成功后刷新 ERP 页面即可生效。
-- ============================================================

-- 一条 key 一行：公司抬头 / 打印设置 / 价格规则 / 品牌图标 / 菜单排序
CREATE TABLE IF NOT EXISTS "systemSettings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "key" text NOT NULL UNIQUE,
  "value" jsonb,
  "updatedAt" text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_syssettings_key ON "systemSettings"("key");

-- 让前端（publishable / anon key）可读写。
-- 与其它业务表一致：第一版暂不开 RLS，应用层自有登录保护。
GRANT ALL ON "systemSettings" TO anon;
GRANT ALL ON SEQUENCE "systemSettings_id_seq" TO anon;

-- 验证：执行后应看到 systemSettings 一行
SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename = 'systemSettings';`

/** Supabase 控制台 → 本项目的 SQL Editor，直接打开就能粘贴执行 */
export const SUPABASE_SQL_EDITOR_URL = (() => {
  try {
    // https://<项目ref>.supabase.co → supabase.com/dashboard/project/<项目ref>/sql/new
    const ref = new URL(SUPABASE_URL).hostname.split('.')[0]
    return `https://supabase.com/dashboard/project/${ref}/sql/new`
  } catch {
    // URL 解析失败（理论上不会发生）：退回控制台首页，不让按钮点了没反应
    return 'https://supabase.com/dashboard'
  }
})()

/**
 * 复制文本到剪贴板。返回是否成功 —— 失败时调用方给用户「请手动选择复制」的提示，
 * 不能让按钮点了像没反应（非 https / 老浏览器下 navigator.clipboard 不存在）。
 */
export async function copyText(text: string): Promise<boolean> {
  try {
    if (typeof navigator !== 'undefined' && navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text)
      return true
    }
  } catch {
    /* 落到下面的兜底方案 */
  }
  try {
    if (typeof document === 'undefined') return false
    const ta = document.createElement('textarea')
    ta.value = text
    ta.setAttribute('readonly', '')
    ta.style.position = 'fixed'
    ta.style.top = '-1000px'
    document.body.appendChild(ta)
    ta.select()
    const ok = document.execCommand('copy')
    document.body.removeChild(ta)
    return ok
  } catch {
    return false
  }
}
